/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.ochmanski.immutables;

import de.ochmanski.immutables.immutable.ImmutableList;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;

class LibraryTest
{

    @Test
    void someLibraryMethodReturnsTrue()
    {
      ImmutableList<StringWrapper> classUnderTest = ImmutableList.<StringWrapper>builder().build();
        Assertions.assertThat(classUnderTest).isNotNull();
    }

}
