/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.ochmanski.immutables;

import de.ochmanski.immutables.immutable.ImmutableList;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class LibraryTest {

  @Test
  void someLibraryMethodReturnsTrue() {
    ImmutableList<String> classUnderTest = ImmutableList.<String>builder().build();
    assertThat(classUnderTest).isNotNull();
    assertThat(classUnderTest.isEmpty()).isTrue();
  }
}
